services:
  - type: web
    name: eventx-api
    env: python
    buildCommand: cd back && pip install -r requirements.txt
    startCommand: cd back && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        value: sqlite:///./eventx.db
    disk:
      name: eventx-db
      mountPath: /opt/render/project/src
      sizeGB: 1

  - type: static
    name: eventx-front
    buildCommand: cd front && npm install && npm run build
    staticPublishPath: front/dist
    envVars:
      - key: VITE_API_URL
        value: https://eventx-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
